name: Deploy to Server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: [Hello, World, Goodbye, Universe]
      
    steps:
      - name: Print Message
        run: echo "${{ matrix.message }}"
          


